In [13]:
import pandas as pd
import numpy as np
from ucimlrepo import fetch_ucirepo

In [82]:
# fetch dataset
tic_tac_toe_endgame = fetch_ucirepo(id=101)

# data (as pandas dataframes)
X = tic_tac_toe_endgame.data.features
y = tic_tac_toe_endgame.data.targets

In [72]:
def stump(X, column=None):
    if column == None:
        return True
    return X[column] == 1


def taxa_acerto(X, y, column):

    return

In [75]:
X

,top-left-square,top-middle-square,top-right-square,middle-left-square,middle-middle-square,middle-right-square,bottom-left-square,bottom-middle-square,bottom-right-square
0,1,1,1,1,-1,-1,1,-1,-1
1,1,1,1,1,-1,-1,-1,1,-1
2,1,1,1,1,-1,-1,-1,-1,1
3,1,1,1,1,-1,-1,-1,0,0
4,1,1,1,1,-1,-1,0,-1,0
...,...,...,...,...,...,...,...,...,...
953,-1,1,1,1,-1,-1,-1,1,1
954,-1,1,-1,1,1,-1,1,-1,1
955,-1,1,-1,1,-1,1,1,-1,1
956,-1,1,-1,-1,1,1,1,-1,1
957,-1,-1,1,1,1,-1,-1,1,1

In [73]:
stump(X, "top-middle-square")

0       True
1       True
2       True
3       True
4       True
       ...
953     True
954     True
955     True
956     True
957    False
Name: top-middle-square, Length: 958, dtype: bool